# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d73ad28c7f362a2f5d014078901726595a843cffa2f886d514b9d71693f7773cb50d2ca3e9efe3f01b7182c478c775ecddbc46ae569d319fbefd4e198f015b16

test:
  secret_key_base: 1ce9802c3800d4c5c3d98e5915fcf494c031f8da998bed3c00d5c1def5c4653bb89ca921c7a7a3bf450c70ebb23373ae8712943568463089bf87e30401481762

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
